# Generated by Django 4.2.11 on 2024-04-16 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, verbose_name='Име')),
            ],
            options={
                'verbose_name': 'Група стоки',
                'verbose_name_plural': 'Групи стоки',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, verbose_name='Име')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='main.group', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория стоки',
                'verbose_name_plural': 'Категории стоки',
            },
        ),
    ]
