# Generated by Django 4.2.11 on 2024-04-16 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='brand',
            new_name='group',
        ),
    ]
