# Generated by Django 4.2.11 on 2024-04-17 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_brand_category_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_rn', to='main.group', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Име')),
                ('description', models.TextField(blank=True, default='', help_text='Текст на отзива', verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Цена')),
                ('new_item', models.BooleanField(default=True, verbose_name='Нов продукт')),
                ('photo', models.ImageField(blank=True, upload_to='items', verbose_name='Снимка')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_category', to='main.category', verbose_name='Категория')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_group', to='main.group', verbose_name='Група')),
            ],
            options={
                'verbose_name': 'Стока',
                'verbose_name_plural': 'Стоки',
            },
        ),
    ]
